
name: CI/CD Pipeline for Angular and Spring Boot

on:
  push:
    branches:
      - main

jobs:
  merge_to_production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge main into production
        run: |
          git checkout production
          git merge main
          git push origin production

  build_and_push_images:
    needs: merge_to_production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout production branch
        uses: actions/checkout@v3
        with:
          ref: production

      - name: Build and push Backend (Spring Boot) Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/springboot-backend:latest ./backend
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/springboot-backend:latest

      - name: Build and push Frontend (Angular) Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/angular-frontend:latest ./frontend
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/angular-frontend:latest

  deploy_to_server:
    needs: build_and_push_images
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to local server via SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd C:/Users/chira/Documents/Pro/Mon_CRM
            docker-compose pull
            docker-compose up -d
