name: CI/CD Pipeline for Angular and Spring Boot

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  merge_to_production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0  # Récupère tout l'historique et toutes les branches

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge main into production
        run: |
          git fetch origin  # Assure que la branche production est récupérée
          if git rev-parse --verify production; then
            git checkout production
          else
            git checkout -b production origin/production
          fi

          git merge main --no-commit --no-ff  # Effectue la fusion sans commettre automatiquement
          git restore --staged .github/workflows/  # Réinitialise les workflows pour ne pas les inclure dans le commit

          # Vérifier s'il y a des changements à commettre
          if git diff-index --quiet HEAD; then
            echo "Rien à commettre, l'arbre de travail est propre."
          else
            git commit -m "Merge main into production, excluding workflow changes"
            git push origin production  # Pousse la branche fusionnée
          fi  # Fin de la vérification des changements

  build_and_push_images:
    needs: merge_to_production
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout production branch
        uses: actions/checkout@v3
        with:
          ref: production
          fetch-depth: 0  # Récupère tout l'historique et toutes les branches

      - name: Check Docker username
        run: |
          echo "Docker Username: ${{ env.DOCKER_USERNAME }}"  # Vérification du nom d'utilisateur Docker

      - name: Docker login to Docker Hub
        run: |
          echo "${{ env.DOCKER_PASSWORD }}" | docker login -u "${{ env.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Backend (Spring Boot) Docker image
        run: |
          docker build -t chirack96/springboot-app:latest ./dev || { echo "Docker build failed"; exit 1; }
          docker push chirack96/springboot-app:latest || { echo "Docker push failed"; exit 1; }

      - name: Build and push Frontend (Angular) Docker image
        run: |
          docker build -t chirack96/angular-app:latest ./Frontend || { echo "Docker build failed"; exit 1; }
          docker push chirack96/angular-app:latest || { echo "Docker push failed"; exit 1; }

      - name: Clean up Docker images
        run: |
          docker image prune -f

  deploy_to_server:
    needs: build_and_push_images
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploy to local server via SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd C:/Users/chira/Documents/Pro/Mon_CRM
            docker-compose pull
            docker-compose up -d
